package generator

import (
	"fmt"
)

// SharedGoogleProtobufGenerator handles generation of shared Google protobuf type definitions
type SharedGoogleProtobufGenerator struct {
	outputDir string
	generatedContent string
}

// NewSharedGoogleProtobufGenerator creates a new shared Google protobuf generator
func NewSharedGoogleProtobufGenerator(outputDir string) *SharedGoogleProtobufGenerator {
	return &SharedGoogleProtobufGenerator{
		outputDir: outputDir,
	}
}

// GenerateSharedGoogleProtobuf generates a shared Google protobuf library file
func (sgpg *SharedGoogleProtobufGenerator) GenerateSharedGoogleProtobuf(protobufLibImportPath string) error {
	// Generate the shared library content
	b := NewWriteableBuffer()

	// Generate file header
	b.P("// File automatically generated by protoc-gen-sol v0.3.0")
	b.P("// SPDX-License-Identifier: CC0")
	b.P("pragma solidity ^0.8.19;")
	b.P0()

	b.P(fmt.Sprintf("import \"%s\";", protobufLibImportPath))
	b.P0()

	// Generate shared Google protobuf library
	b.P("// Shared Google protobuf type definitions")
	b.P("library Google_Protobuf {")
	b.Indent()

	// Generate struct definitions for commonly used Google protobuf types
	googleTypes := NewGoogleProtobufTypes()
	googleTypes.GenerateAllTypes(b)

	b.Unindent()
	b.P("}")

	// Store the generated content
	sgpg.generatedContent = b.String()
	return nil
}

// GetGeneratedContent returns the generated content
func (sgpg *SharedGoogleProtobufGenerator) GetGeneratedContent() string {
	return sgpg.generatedContent
}


